import { Router } from 'express'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { z } from 'zod'
import { Admin, Patient, Visit } from '../models'
import { config, syncPatientAggregates } from '../config'
import { auth } from '../middleware/auth'

const router = Router(); const medicine = z.object({ medicineName: z.string().min(1), tradePrice: z.number().nonnegative(), sellingPrice: z.number().nonnegative(), quantity: z.number().nonnegative().default(1) }); const patient = z.object({ name: z.string().min(1), phone: z.string().min(3), age: z.number().int().nonnegative().max(150).optional(), gender: z.string().optional(), address: z.string().optional() }); const visit = z.object({ visitDate: z.coerce.date().optional(), diagnosis: z.string().optional(), notes: z.string().optional(), medicines: z.array(medicine).default([]) })
router.post('/auth/login', async (req,res,next)=>{ try { const body=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body); const admin=await Admin.findOne({email:body.email}); if(!admin || !(await bcrypt.compare(body.password,admin.passwordHash))) return res.status(401).json({error:{code:'UNAUTHORIZED',message:'Invalid credentials'}}); res.json({data:{token:jwt.sign({sub:admin.id,email:admin.email},process.env.JWT_SECRET || config.jwtSecret,{expiresIn:'8h'})}}) } catch(e){next(e)} })
router.use(auth)
router.post('/patients',async(req,res,next)=>{try{const p=await Patient.create(patient.parse(req.body));res.status(201).json({data:p})}catch(e){next(e)}})
router.get('/patients',async(req,res,next)=>{try{const search=String(req.query.search||'').trim();const q=search?{$text:{$search:search}}:{};res.json({data:await Patient.find(q).sort({createdAt:-1})})}catch(e){next(e)}})
router.get('/patients/:id',async(req,res,next)=>{try{const p=await Patient.findById(req.params.id);if(!p)return res.status(404).json({error:{code:'NOT_FOUND',message:'Patient not found'}});const visits=await Visit.find({patientId:p._id}).sort({visitDate:-1});res.json({data:{patient:p,visits}})}catch(e){next(e)}})
router.put('/patients/:id',async(req,res,next)=>{try{const p=await Patient.findByIdAndUpdate(req.params.id,patient.partial().parse(req.body),{new:true,runValidators:true});if(!p)return res.status(404).json({error:{code:'NOT_FOUND',message:'Patient not found'}});res.json({data:p})}catch(e){next(e)}})
router.post('/patients/:id/visits',async(req,res,next)=>{try{const data=visit.parse(req.body);const p=await Patient.findById(req.params.id);if(!p)return res.status(404).json({error:{code:'NOT_FOUND',message:'Patient not found'}});const v=await Visit.create({...data,patientId:p._id});await syncPatientAggregates(String(p._id));res.status(201).json({data:v})}catch(e){next(e)}})
router.put('/patients/:patientId/visits/:visitId',async(req,res,next)=>{try{const data=visit.partial().parse(req.body);const v=await Visit.findOne({_id:req.params.visitId,patientId:req.params.patientId});if(!v)return res.status(404).json({error:{code:'NOT_FOUND',message:'Visit not found'}});if(data.visitDate!==undefined)v.visitDate=data.visitDate;if(data.diagnosis!==undefined)v.diagnosis=data.diagnosis;if(data.notes!==undefined)v.notes=data.notes;if(data.medicines!==undefined)v.medicines=data.medicines;await v.save();await syncPatientAggregates(req.params.patientId);res.json({data:v})}catch(e){next(e)}})
router.delete('/patients/:patientId/visits/:visitId',async(req,res,next)=>{try{const v=await Visit.findOneAndDelete({_id:req.params.visitId,patientId:req.params.patientId});if(!v)return res.status(404).json({error:{code:'NOT_FOUND',message:'Visit not found'}});await syncPatientAggregates(req.params.patientId);res.json({data:{deleted:true}})}catch(e){next(e)}})
router.get('/reports/summary',async(req,res,next)=>{try{const from=req.query.from?new Date(String(req.query.from)):new Date(0);const to=req.query.to?new Date(String(req.query.to)):new Date();const [summary,top,byDay]=await Promise.all([Visit.aggregate([{$match:{visitDate:{$gte:from,$lte:to}}},{$group:{_id:null,totalProfit:{$sum:'$visitTotalProfit'},totalVisits:{$sum:1}}}]),Visit.aggregate([{$match:{visitDate:{$gte:from,$lte:to}}},{$unwind:'$medicines'},{$group:{_id:'$medicines.medicineName',profit:{$sum:'$medicines.profit'},quantity:{$sum:'$medicines.quantity'}}},{$sort:{profit:-1}},{$limit:10}]),Visit.aggregate([{$match:{visitDate:{$gte:from,$lte:to}}},{$group:{_id:{$dateToString:{format:'%Y-%m-%d',date:'$visitDate'}},profit:{$sum:'$visitTotalProfit'},visits:{$sum:1}}},{$sort:{_id:1}}])]);res.json({data:{summary:summary[0]||{totalProfit:0,totalVisits:0},topMedicines:top,byDay}})}catch(e){next(e)}})
export default router
