import request from 'supertest'
import { MongoMemoryServer } from 'mongodb-memory-server'
import mongoose from 'mongoose'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { app } from '../src/app'
import { Admin, Patient, Visit } from '../src/models'
let mongo:MongoMemoryServer; const secret='test-secret'; const token=jwt.sign({sub:'admin'},secret)
beforeAll(async()=>{process.env.JWT_SECRET=secret;mongo=await MongoMemoryServer.create();await mongoose.connect(mongo.getUri());await Admin.create({email:'doctor@example.com',passwordHash:await bcrypt.hash('password',10)});await Patient.syncIndexes()}, 30000)
afterAll(async()=>{await mongoose.disconnect();await mongo.stop()})
test('health is public',async()=>{expect((await request(app).get('/health')).status).toBe(200)})
test('rejects missing auth',async()=>{expect((await request(app).get('/api/patients')).status).toBe(401)})
test('creates patient without phone or address',async()=>{const h={Authorization:`Bearer ${token}`};const res=await request(app).post('/api/patients').set(h).send({name:'No Phone Patient'});expect(res.status).toBe(201);expect(res.body.data.name).toBe('No Phone Patient');expect(res.body.data.phone).toBe('')})
test('creates patient, visit, and keeps totals in sync',async()=>{const h={Authorization:`Bearer ${token}`};const p=(await request(app).post('/api/patients').set(h).send({name:'Test Patient',phone:'555-0100'})).body.data;await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'A',tradePrice:4,sellingPrice:10,quantity:2},{medicineName:'B',tradePrice:12,sellingPrice:10,quantity:1}]});await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'C',tradePrice:1,sellingPrice:3,quantity:1}]});const saved=await Patient.findById(p._id);const visits=await Visit.find({patientId:p._id});expect(saved?.totalVisits).toBe(2);expect(saved?.totalProfit).toBe(visits.reduce((s,v)=>s+v.visitTotalProfit,0));expect(saved?.totalTradePrice).toBe(visits.reduce((s,v)=>s+v.visitTotalTradePrice,0));expect(saved?.totalSellingPrice).toBe(visits.reduce((s,v)=>s+v.visitTotalSellingPrice,0))})
test('updates and deletes visits while keeping patient totals in sync',async()=>{const h={Authorization:`Bearer ${token}`};const p=(await request(app).post('/api/patients').set(h).send({name:'Edit Patient',phone:'555-0200'})).body.data;const v1=(await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({diagnosis:'Initial',medicines:[{medicineName:'A',tradePrice:2,sellingPrice:5,quantity:1}]})).body.data;const v2=(await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'B',tradePrice:1,sellingPrice:4,quantity:2}]})).body.data;const updated=(await request(app).put(`/api/patients/${p._id}/visits/${v1._id}`).set(h).send({diagnosis:'Updated diagnosis',medicines:[{medicineName:'A',tradePrice:2,sellingPrice:8,quantity:1}]})).body.data;expect(updated.diagnosis).toBe('Updated diagnosis');expect(updated.visitTotalProfit).toBe(6);let saved=await Patient.findById(p._id);expect(saved?.totalVisits).toBe(2);expect(saved?.totalProfit).toBe(6+6);expect((await request(app).delete(`/api/patients/${p._id}/visits/${v2._id}`).set(h)).status).toBe(200);saved=await Patient.findById(p._id);const visits=await Visit.find({patientId:p._id});expect(saved?.totalVisits).toBe(1);expect(saved?.totalProfit).toBe(visits.reduce((s,v)=>s+v.visitTotalProfit,0))})
test('updates patient demographics',async()=>{const h={Authorization:`Bearer ${token}`};const p=(await request(app).post('/api/patients').set(h).send({name:'Before',phone:'555-0300'})).body.data;const updated=(await request(app).put(`/api/patients/${p._id}`).set(h).send({name:'After',age:42,gender:'M',address:'123 Main St'})).body.data;expect(updated.name).toBe('After');expect(updated.age).toBe(42);expect(updated.gender).toBe('M');expect(updated.address).toBe('123 Main St')})
test('deletes patient and all visits',async()=>{const h={Authorization:`Bearer ${token}`};const p=(await request(app).post('/api/patients').set(h).send({name:'Delete Me',phone:'555-0400'})).body.data;await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'A',tradePrice:2,sellingPrice:5,quantity:1}]});await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'B',tradePrice:1,sellingPrice:4,quantity:2}]});expect((await request(app).delete(`/api/patients/${p._id}`).set(h)).status).toBe(200);expect(await Patient.findById(p._id)).toBeNull();expect(await Visit.find({patientId:p._id})).toHaveLength(0);expect((await request(app).delete(`/api/patients/${p._id}`).set(h)).status).toBe(404)})
test('stores optional medicine schedule on visits',async()=>{const h={Authorization:`Bearer ${token}`};const p=(await request(app).post('/api/patients').set(h).send({name:'Schedule Patient'})).body.data;const visit=(await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'Vitamin C',tradePrice:10,sellingPrice:20,quantity:1,morning:true,noon:true},{medicineName:'Ibuprofen',tradePrice:5,sellingPrice:12,quantity:2}]})).body.data;expect(visit.medicines[0].morning).toBe(true);expect(visit.medicines[0].noon).toBe(true);expect(visit.medicines[0].night).toBe(false);expect(visit.medicines[1].morning).toBe(false);const saved=(await request(app).get(`/api/patients/${p._id}`).set(h)).body.data;expect(saved.visits[0].medicines[0].morning).toBe(true);expect(saved.visits[0].medicines[1].night).toBe(false)})
test('stores checkup fee per visit and totals it on the patient',async()=>{const h={Authorization:`Bearer ${token}`};const p=(await request(app).post('/api/patients').set(h).send({name:'Checkup Patient'})).body.data;const v1=(await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({checkupFee:200,medicines:[{medicineName:'A',tradePrice:2,sellingPrice:5,quantity:1}]})).body.data;expect(v1.checkupFee).toBe(200);await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({checkupFee:150,medicines:[{medicineName:'B',tradePrice:1,sellingPrice:3,quantity:1}]});const ignored=(await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'check up',tradePrice:0,sellingPrice:250,quantity:1}]})).body.data;expect(ignored.checkupFee).toBe(0);const saved=await Patient.findById(p._id);expect(saved?.totalCheckupFee).toBe(350)})
test('login returns JWT',async()=>{const r=await request(app).post('/api/auth/login').send({email:'doctor@example.com',password:'password'});expect(r.status).toBe(200);expect(r.body.data.token).toEqual(expect.any(String))})
test('searches medicines from prior visits',async()=>{const h={Authorization:`Bearer ${token}`};const p=(await request(app).post('/api/patients').set(h).send({name:'Med Search Patient'})).body.data;await request(app).post(`/api/patients/${p._id}/visits`).set(h).send({medicines:[{medicineName:'Amoxicillin 500mg',tradePrice:50,sellingPrice:120,quantity:1}]});const empty=await request(app).get('/api/medicines/search?q=').set(h);expect(empty.status).toBe(200);expect(empty.body.data).toEqual([]);const found=await request(app).get('/api/medicines/search?q=amox').set(h);expect(found.status).toBe(200);expect(found.body.data).toHaveLength(1);expect(found.body.data[0].medicineName).toBe('Amoxicillin 500mg');expect(found.body.data[0].tradePrice).toBe(50);expect(found.body.data[0].sellingPrice).toBe(120)})
test('creates the patient search index',async()=>{await Patient.init();await Patient.createIndexes();const indexes=await Patient.collection.indexes();expect(indexes.some((index)=>index.name==='patient_search_text'&&(index.weights?.name===1||index.key?.name==='text'))).toBe(true)})
